[project]
name = "ccpm-simulator"
version = "0.1.0"
description = "Critical Chain Project Management (CCPM) simulator in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numpy>=2.2.4",
    "pandas",
]
